# Generated by Django 5.2.13 on 2026-05-06 23:14

import app.models
import django.db.models.deletion
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='name')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('ready', 'ready'), ('ongoing', 'ongoing'), ('done', 'done')], db_index=True, default='draft', max_length=8, verbose_name='status')),
                ('level', models.SmallIntegerField(blank=True, choices=[(1, 'easy'), (2, 'medium'), (3, 'hard'), (4, 'extreme'), (5, 'nightmare')], db_index=True, null=True, verbose_name='level')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='score')),
                ('subscription_date', models.DateField(blank=True, null=True, verbose_name='subscription date')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True, verbose_name='creation datetime')),
                ('last_modification_datetime', models.DateTimeField(auto_now=True, verbose_name='last modification datetime')),
                ('profile_activated', models.BooleanField(verbose_name='profile activated')),
                ('avatar', models.ImageField(blank=True, max_length=256, null=True, upload_to=functools.partial(app.models.compute_upload_path, *(), **{'sub_path': 'avatar'}), verbose_name='avatar')),
                ('signed_engagement', models.FileField(blank=True, max_length=256, null=True, upload_to=functools.partial(app.models.compute_upload_path, *(), **{'sub_path': 'signed_engagement'}), verbose_name='signed_engagement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
                'ordering': ('user__username',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='question content')),
                ('points', models.PositiveSmallIntegerField(verbose_name='points')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='app.game', verbose_name='game')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ('game_id', 'order'),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='answer content')),
                ('points', models.PositiveSmallIntegerField(default=0, verbose_name='points')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='app.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'ordering': ('question_id', 'order'),
            },
        ),
    ]
